version: "3"

services:
  app:
    # image: demoapp
    build: .
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000-3010:3000"
    volumes:
      # Bindea a esta ruta
      - .:/usr/src
      # Si no tiene 2 puntos no sobreescribe nada
      - /usr/src/node_modules

  db:
    image: mongo
